---
- name: Создание директории для WordPress
  ansible.builtin.file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Скачивание WordPress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    timeout: 30

- name: Распаковка WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes
    creates: /tmp/wordpress

- name: Копирование файлов в целевую директорию
  ansible.builtin.copy:
    src: /tmp/wordpress/
    dest: /var/www/wordpress/
    remote_src: yes
    owner: www-data
    group: www-data
    mode: '0644'

- name: Создание конфигурации wp-config.php из шаблона
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
